#!/bin/sh

set -ex

INTERNAL_VERSION="$1"
STACK_VERSION="$2"

docker build \
  -t flipstone/stack:$INTERNAL_VERSION-$STACK_VERSION \
  $INTERNAL_VERSION/$STACK_VERSION

echo "Build Complete. If you release this build, please remember to update the README.md file to document the release."
